CTCP-2794: Add handle error endpoint to cache
hmrc/manage-transit-movements-departure-cache pull request #52
Opened 2023-05-05 12:56 UTC by Reece-Carruthers

2023-05-09 10:16 UTC, jackheslop96 commented on app/models/XPath.scala
> +      case x if x.matches("^TransitOperation/securityDetailsType$")      => PreTaskList
Be careful not to get mixed up between the user answers paths and the xpaths. If the xsds are to be believed these should be `TIRCarnetNumber` and `security` (https://github.com/hmrc/manage-transit-movements-departure-cache/blob/780d954d67a2af39fabbb3676492ed6ad3fd56cf/conf/xsd/ctypes.xsd#L19179 and https://github.com/hmrc/manage-transit-movements-departure-cache/blob/780d954d67a2af39fabbb3676492ed6ad3fd56cf/conf/xsd/ctypes.xsd#L19199) cc @Reece-Carruthers @MatthewAlexanderBeck

2023-05-10 08:41 UTC, MatthewAlexanderBeck requested changes

2023-05-10 08:41 UTC, MatthewAlexanderBeck commented on app/models/XPath.scala
> +      case x if x.matches("^Consignment/HouseConsignment(\\[[\\d]*])/ConsingmentItem(.+)$")                                => Items
ConsingmentItem

2023-05-11 07:41 UTC, MatthewAlexanderBeck approved these changes

2023-05-12 13:11 UTC, MatthewAlexanderBeck approved these changes

2023-05-15 07:31 UTC, merged